name: Run Python script

on:
  schedule:
    - cron: "01 4 * * *"  # 18:00 IST = 12:30 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # skip if no requirements

    - name: Run Python script
      run: python Test.py  # Use correct case-sensitive filename
